locals {
  resource_prefix                        = "${var.name_prefix}-${var.environment_name}"
  access_key_function_name               = "${local.resource_prefix}-access-key-enforcement"
  access_key_recovery_name               = "${local.resource_prefix}-access-key-recovery-request"
  access_key_recovery_api                = "${local.resource_prefix}-access-key-recovery-api"
  download_tracker_name                  = "${local.resource_prefix}-download-tracker"
  url_regenerator_name                   = "${local.resource_prefix}-url-regenerator"
  cleanup_name                           = "${local.resource_prefix}-cleanup"
  s3_cleanup_name                        = "${local.resource_prefix}-s3-cleanup"
  credentials_bucket_name                = "${local.resource_prefix}-${var.account_id}-credentials"
  cloudtrail_bucket_name                 = "${local.resource_prefix}-${var.account_id}-cloudtrail"
  access_logs_bucket_name                = "${local.resource_prefix}-${var.account_id}-access-logs"
  tracking_table_name                    = "${local.resource_prefix}-tracking"
  enforcement_rule_name                  = "${local.resource_prefix}-enforcement-daily"
  url_regenerator_rule_name              = "${local.resource_prefix}-url-regenerator-daily"
  cleanup_rule_name                      = "${local.resource_prefix}-cleanup-daily"
  s3_cleanup_rule_name                   = "${local.resource_prefix}-s3-cleanup-daily"
  download_events_rule_name              = "${local.resource_prefix}-download-events"
  trail_name                             = "${local.resource_prefix}-download-tracking"
  cloudtrail_log_group_name              = "/aws/cloudtrail/${local.trail_name}"
  cloudtrail_trail_arn                   = "arn:aws:cloudtrail:${var.aws_region}:${var.account_id}:trail/${local.trail_name}"
  alarm_sns_topic_name                   = element(split(":", var.alarm_sns_topic), 5)
  expired_alarm_name                     = "${local.resource_prefix}-expired-keys"
  urgent_alarm_name                      = "${local.resource_prefix}-urgent-keys"
  dynamodb_alarm_name                    = "${local.resource_prefix}-tracking-user-errors"
  access_key_recovery_route_key          = "POST /access-key-recovery/request"
  access_key_recovery_api_log_group_name = "/aws/apigateway/${local.access_key_recovery_api}"
  access_key_recovery_api_4xx_alarm_name = "${local.resource_prefix}-access-key-recovery-api-4xx"
  access_key_recovery_api_5xx_alarm_name = "${local.resource_prefix}-access-key-recovery-api-5xx"
  log_retention_days                     = 365
  lambda_reserved_concurrency = {
    access_key_enforcement = 5
    access_key_recovery    = 5
    download_tracker       = 20
    url_regenerator        = 5
    cleanup                = 2
    s3_cleanup             = 2
  }
}
